language: java
jdk:
  - oraclejdk8
script: mvn clean package -Dspring.profiles.active=bitbucketpipelines -Dspring.datasource.password=
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE springtutorialmovies;'