pipelines:
  branches:
    master:
      - step:
          image: maven:3.3.9
          script:
            - sleep 10 # Wait for Database to start
            - mvn clean package -Dspring.profiles.active=bitbucketpipelines
          services:
            - database
definitions:
  services:
    database:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root       