image: maven:3.3.9

pipelines:
  default:
    - step:
        script: 
          - mvn clean package -Dspring.profiles.active=ci
definitions:
  services:
    database:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root
          